language: go
sudo: false
go: 1.13
before_install:
  # Install Kafka deps
  - wget -qO - https://packages.confluent.io/deb/5.4/archive.key | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.4 stable main"
  - sudo apt-get update
  - sudo apt-get install -y librdkafka-dev

  # Install golangci-lint
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  # Lint the codebase
  - $GOPATH/bin/golangci-lint run --deadline=1m

  # Run any tests in the repo
  - go test -v ./...
