language: go
sudo: false
go: 1.14
cache:
  directories:
    - $GOPATH/pkg/mod
before_install:
- wget -qO - https://packages.confluent.io/deb/5.4/archive.key | sudo apt-key add
  -
- sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.4
  stable main"
- sudo apt-get update
- sudo apt-get install -y librdkafka-dev
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
  | sh -s -- -b $(go env GOPATH)/bin v1.24.0
script:
- "$GOPATH/bin/golangci-lint run --deadline=1m"
- go test -v ./...
