version: '3.5'
volumes:
  zookeeper-data:
    name: ortelius_zookeeper_data
  zookeeper-log:
    name: ortelius_zookeeper_logs
  kafka-data:
    name: ortelius_kafka
  redis-data:
    name: ortelius_redis
  mysql-data:
    name: ortelius_mysql
  avalanche-data:
    name: ortelius_avalanche
  avalanche-ipcs:
    name: ortelius_avalanche_ipcs
networks:
  default:
    name: ortelius_services
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    ports:
      - 2181
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_SERVERS=zookeeper:4182:5181
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data/
      - zookeeper-log:/var/lib/zookeeper/log/
    healthcheck:
      test: /bin/sh -c '[ \"imok\" = \"$$(echo ruok | nc -w 1 127.0.0.1 2181)\" ]' || exit 1
      interval: 1m
    restart: on-failure
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    env_file:
      - kafka.env
    volumes:
      - kafka-data:/var/lib/kafka/data/
    restart: on-failure
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ortelius_dev
    restart: on-failure
  migrate:
    image: migrate/migrate:v4.11.0
    volumes:
      - ../../services/db/migrations:/migrations
      - ./migrate.sh:/migrate.sh
    depends_on:
      - mysql
    entrypoint: ["/bin/sh"]
    command: ["/migrate.sh"]
    restart: on-failure
  redis:
    image: "redis:6.0.5-alpine3.12"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
    restart: on-failure
  avalanche:
    image: "avaplatform/avalanchego:a7890896"
    command: [
      "./build/avalanchego",
      "-db-dir=/var/lib/avalanche",
      "-log-level=info",
      "-ipcs-chain-ids=11111111111111111111111111111111LpoYY,jnUjZSRt16TcRnZzmh5aMhavwVHz3zBrSN8GfFMTQkzUnoBxC",
    ]
    volumes:
      - avalanche-data:/var/lib/avalanche
      - avalanche-ipcs:/tmp
    restart: always
