---

name: build-check
on: [push, pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  test-and-build:
    name: Test and build on Go ${{ matrix.go }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go:
          - '1.15'
          - '1.14'
          - '1.13'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Test binary build
        run: go build cmds/orteliusd/orteliusd.go
      - name: Run tests
        run: make tests
      - name: Save test coverage
        uses: shogo82148/actions-goveralls@v1
        if: matrix.go == '1.15'
        with:
          path-to-profile: coverage.out
